# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: beta-xcode6.3
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: 
  - bundler
  - cocoapods

before_install:
 - rvm install ruby-2.1.3
 - rvm use 2.1.3
 - brew update && brew install carthage
 - bundle install
install: 
 - bundle exec pod install
 - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
 - set -o pipefail && xcodebuild test -workspace Rec.xcworkspace -scheme Rec -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
 - set -o pipefail && xcodebuild test -workspace Rec.xcworkspace -scheme Rec-OSX -sdk macosx ONLY_ACTIVE_ARCH=NO | xcpretty -c
after_success: bundle exec slather
