# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
cache: cocoapods
podfile: RecExample/Podfile

before_install:
 - rvm use 2.1.3
 - bundle install --without=documentation --path=vendor
install:
 - bundle exec pod install --project-directory=RecExample/
script:
 - set -o pipefail && xcodebuild test -workspace Rec.xcworkspace -scheme RecExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
 - pod lib lint --quick
after_success: bundle exec slather
