# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
cache: cocoapods

before_install:
 - rvm use 2.1.3
 - bundle install --without=documentation --path=vendor
script:
 - set -o pipefail && bundle exec xcodebuild test -workspace Rec.xcworkspace -scheme Rec -sdk iphonesimulator8.3 ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty -c
after_success: bundle exec slather
